---
title: "Trabalho Econometria II"
author: "Grupo 6"
date: "20/01/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Lendo o arquivo e ajustando o período de tempo da base
library(tidyverse)
library(readr)
emprego <- read_csv("C:/Users/angel/Downloads/ipeadata[20-01-2021-02-19].csv")
emprego <- emprego %>% 
  rename(Saldo = `Empregados - saldo - Pessoa - Ministério do Trabalho e Emprego- Cadastro Geral de Empregados e Desempregados (MTE/CAGED) - CAGED12_SALDO12`) %>% 
  select(Data, Saldo)
emprego <- emprego %>% 
  filter(Data > 2000.01)
emprego_ts <- ts(emprego, start = c(2000, 1), frequency = 12)
```

```{r}
##################################### PARTE 1: IDENTIFICAÇÃO DA SÉRIE
# plotando o gráfico da série temporal
plot(emprego_ts[,2], xlab = "Período", ylab = "Saldo",
     main = "Saldo de empregos formais ao longo dos anos")
# Decompondo a série
plot(decompose(emprego_ts[,2]))

# pacote para teste de raíz unitária
library(urca)
par(mfrow = c(1,1))
# FAC e FACP em nível
acf(emprego_ts[,2], xlab = "Defasagem", ylab = "FAC", 
    main = "Função de autocorrelação (em nível)", lag.max = 48)
pacf(emprego_ts[,2], xlab = "Defasagem", ylab = "FACP",
     main = "Função de autocorrelação parcial (em nível)", lag.max = 48)
# teste de raíz unitária (ADF) - variável em nível - não estacionário
summary(ur.df(emprego_ts[,2], type = c("none"), lags = 24, selectlags = "BIC"))
summary(ur.df(emprego_ts[,2], type = c("drift"), lags = 24, selectlags = "BIC"))
summary(ur.df(emprego_ts[,2], type = c("trend"), lags = 24, selectlags = "BIC"))
# teste de raíz unitária (PP) - variável em nível - estacionário
summary(ur.pp(emprego_ts[,2], type = c("Z-tau"), model = c("constant"), lags = c("short")))
summary(ur.pp(emprego_ts[,2], type = c("Z-tau"), model = c("trend"), lags = c("short")))
# teste de raíz unitária (KPSS) - variável em nível - não estacionário
# LEMBRETE: H0 nesse teste é a hipótese de que a variável é estacionária
summary(ur.kpss(emprego_ts[,2], type = c("mu"), lags = c("short")))
summary(ur.kpss(emprego_ts[,2], type = c("tau"), lags = c("short")))

# primeira diferença sazonal da série
plot(diff(emprego_ts[,2], lag = 12, differences = 1), ylab = "", xlab = "Período",
     main = "Primeira diferença sazonal do emprego\nformal no tempo")
# primeira diferença sazonal
acf(diff(emprego_ts[,2], lag = 12), lag.max = 48,
main = "Função de autocorrelação\n(primeira diferença sazonal)", ylab = "FAC", xlab = "Defasagem")
pacf(diff(emprego_ts[,2], lag = 12), lag.max = 48,
main = "Função de autocorrelação parcial\n(primeira diferença sazonal)", ylab = "FACP", xlab = "Defasagem")
# teste de raíz unitária (ADF) - variável em nível e primeira diferença sazonal - estacionário
summary(ur.df(diff(emprego_ts[,2], lag = 12), type = c("none"), lags = 24, selectlags = "BIC"))
summary(ur.df(diff(emprego_ts[,2], lag = 12), type = c("drift"), lags = 24, selectlags = "BIC"))
summary(ur.df(diff(emprego_ts[,2], lag = 12), type = c("trend"), lags = 24, selectlags = "BIC"))
# teste de raíz unitária (PP) - variável em nível e primeira diferença sazonal - estacionário
summary(ur.pp(diff(emprego_ts[,2], lag = 12), type = c("Z-tau"), model = c("constant"), lags = c("short")))
summary(ur.pp(diff(emprego_ts[,2], lag = 12), type = c("Z-tau"), model = c("trend"), lags = c("short")))
# teste de raíz unitária (KPSS) - variável em nível e primeira diferença sazonal - estacionário
# LEMBRETE: H0 nesse teste é a hipótese de que a variável é estacionária
summary(ur.kpss(diff(emprego_ts[,2], lag = 12), type = c("mu"), lags = c("short")))
summary(ur.kpss(diff(emprego_ts[,2], lag = 12), type = c("tau"), lags = c("short")))
```

```{r}
##################################### PARTE 2: ESTIMAÇÃO
# estimação do modelo SARIMA
library(forecast)
library(tseries)
library(FitAR)
library(FinTS)
library(lmtest)

# Modelos candidatos: SARIMA(p,d,q)(P,D,Q) com combinações de ordem d = 0 e D = 1 e  p, P, q, Q
fit1 <- coeftest(Arima(emprego_ts[,2], order = c(1,0,1), seasonal = list(order = c(0,1,0), period = 12))); fit1 
fit2 <- coeftest(Arima(emprego_ts[,2], order = c(1,0,2), seasonal = list(order = c(0,1,0), period = 12))); fit2 
fit3 <- coeftest(Arima(emprego_ts[,2], order = c(2,0,1), seasonal = list(order = c(0,1,0), period = 12))); fit3 # ma1 não significativo
fit4 <- coeftest(Arima(emprego_ts[,2], order = c(2,0,2), seasonal = list(order = c(1,1,0), period = 12))); fit4 # somente sar1 significativo
fit5 <- coeftest(Arima(emprego_ts[,2], order = c(1,0,2), seasonal = list(order = c(1,1,1), period = 12))); fit5 # sar1 não significativo
fit6 <- coeftest(Arima(emprego_ts[,2], order = c(1,0,2), seasonal = list(order = c(1,1,2), period = 12))); fit6 # sma1 não significativo
fit7 <- coeftest(Arima(emprego_ts[,2], order = c(1,0,2), seasonal = list(order = c(2,1,1), period = 12))); fit7 # sar1 e sar não significativos
fit8 <- coeftest(auto.arima(emprego_ts[,2])); fit8 

# Análise dos critérios de informação dos modelos candidatos
# (melhores modelos são os que possuem menor critério de informação)
mod1 <- Arima(emprego_ts[,2], order = c(1,0,1), seasonal = list(order = c(0,1,0), period = 12))
mod2 <- Arima(emprego_ts[,2], order = c(1,0,2), seasonal = list(order = c(0,1,0), period = 12))
mod3 <- Arima(emprego_ts[,2], order = c(2,0,1), seasonal = list(order = c(0,1,0), period = 12))
mod4 <- Arima(emprego_ts[,2], order = c(2,0,2), seasonal = list(order = c(1,1,0), period = 12))
mod5 <- Arima(emprego_ts[,2], order = c(1,0,2), seasonal = list(order = c(1,1,1), period = 12))
mod6 <- Arima(emprego_ts[,2], order = c(1,0,2), seasonal = list(order = c(1,1,2), period = 12))
mod7 <- Arima(emprego_ts[,2], order = c(1,0,2), seasonal = list(order = c(2,1,1), period = 12))
mod8 <- auto.arima(emprego_ts[,2])
# critério Akaike e Bayesiano
AIC(mod1, mod2, mod3, mod4,mod5, mod6, mod7, mod8) # mod5 e mod8
BIC(mod1, mod2, mod3, mod4,mod5, mod6, mod7, mod8) # mod5 e mod8
```

```{r}
##################################### PARTE 3: VERIFICAÇÃO DO MODELO AJUSTADO
# foram verificados os modelos 5 e 8 de acordo com os critérios menores de AIC e BIC 

# Teste de estabilidade
autoplot(mod5)
autoplot(mod7)
autoplot(mod8)

# Testes dos resíduos
res5 <- residuals(mod5)
res7 <- residuals(mod7)
res8 <- residuals(mod8)

## Autocorrelação - Teste de Ljung-Box
##H0: os residuos sao iid
tsdiag(mod5)
Box.test(res5,lag = 12,type = "Ljung-Box")
Box.test(res5,lag = 24,type = "Ljung-Box")
Box.test(res5,lag = 36,type = "Ljung-Box")
Box.test(res5,lag = 48,type = "Ljung-Box")

tsdiag(mod7)
Box.test(res7,lag = 12,type = "Ljung-Box")
Box.test(res7,lag = 24,type = "Ljung-Box")
Box.test(res7,lag = 36,type = "Ljung-Box")
Box.test(res7,lag = 48,type = "Ljung-Box")

tsdiag(mod8)
Box.test(res8,lag = 12,type = "Ljung-Box")
Box.test(res8,lag = 24,type = "Ljung-Box")
Box.test(res8,lag = 36,type = "Ljung-Box")
Box.test(res8,lag = 48,type = "Ljung-Box")

## Normalidade                      
##Teste de Jarque-Bera
##H0: normalidade dos residuos

par(mfrow = c(2,2)) ##colocar 2 em cima e 2 embaixo
hist(res5, freq = F, ylab = 'Densidade', xlab = 'Resíduos', main = 'Resíduos')
plot(density(res5, kernel = c("gaussian")), main="Resíduos")   #Função de densidade estimada
qqnorm(res5, ylab='Quantis amostrais', xlab='Quantis teóricos', main='Quantil-Quantil')
qqline(res5, col = "red")
shapiro.test(res5)
jarque.bera.test(res5)

par(mfrow=c(2,2))
hist(res7, freq=F, ylab='Densidade', xlab='Resíduos', main='Resíduos')
plot(density(res7, kernel = c("gaussian")), main="Resíduos")   #Função de densidade estimada
qqnorm(res7, ylab='Quantis amostrais', xlab='Quantis teóricos', main='Quantil-Quantil')
qqline(res7, col = "red")
shapiro.test(res7)
jarque.bera.test(res7)

par(mfrow=c(1,1))
hist(res8, freq=F, ylab='Densidade', xlab='Resíduos', main='Resíduos')
plot(density(res8, kernel = c("gaussian")), main="Resíduos")   #Função de densidade estimada
qqnorm(res8, ylab='Quantis amostrais', xlab='Quantis teóricos', main='Quantil-Quantil')
qqline(res8, col = "red")
shapiro.test(res8)
jarque.bera.test(res8)


# Teste de Heteroscedasticidade     
##Teste ARCH
##H0: os residuos nao possuem efeitos auto-regressivos de heteroscedasticidade condicional
ArchTest(res5,lags = 12)
ArchTest(res7,lags = 12)
ArchTest(res8,lags = 12)
```

```{r}
library(formattable)
#############################PARTE 4 - PREVISÃO
## Teste de acurácia: dentro da amostra (amostra inteira como treino)
accuracy(mod8)
accuracy(mod5)

## Teste de acurácia: fora da amostra (usando o ano de 2019 como teste)
### Modelo 8
emprego.teste<- tail(emprego_ts[ ,2],12) ## observar apenas as últimas 12 observações                                   # definindo a série "teste"
emprego.teste

emprego.treino <- head(emprego_ts[ ,2], length(emprego_ts[ ,2])-12) ## pegar o começo da série               # definindo a série "treino"
emprego.treino

mod8.treino=auto.arima(emprego.treino); mod8.treino

fc_mod8.treino <- forecast(mod8.treino, h = 12) ## a partir da série treino, realizar a projeção para 12 períodos para frente
fc_mod8.treino
fc_mo8_tabela <- as_tibble(fc_mod8.treino)
formattable(fc_mo8_tabela)
par(mfrow=c(1,1)) ## apenas para organizar os gráficos
plot(fc_mod8.treino, include = 24, showgap = F, main = "Previsão do SARIMA
     (1,0,2)(0,1,1)", xlab = "Período")

accuracy(fc_mod8.treino$mean,emprego.teste)

## criar um data frame
df_test8 <- ts(data.frame(cbind(fcst=fc_mod8.treino$mean,obs=emprego.teste)))

## plotar o observado com a previsão
autoplot(df_test8[,2], series = "Observado") + 
  autolayer(df_test8[,1], series = "Previsão") +
  labs(title = "Emprego CLT (Período: Jan/2019 - Dez/2019)",
       x = "Períodos",
       y = "",
       color = "Previsão")


### Modelo 5

emprego.teste<- tail(emprego_ts[ ,2],12) ## observar apenas as últimas 12 observações                                   # definindo a série "teste"
emprego.teste

emprego.treino <- head(emprego_ts[ ,2], length(emprego_ts[ ,2])-12) ## pegar o começo da série               # definindo a série "treino"
emprego.treino

mod5.treino=Arima(emprego.treino, order=c(1,0,2), seasonal=list(order=c(1,1,1), period=12)); mod5.treino

fc_mod5.treino <- forecast(mod5.treino, h = 12) ## a partir da série treino, realizar a projeção para 12 períodos para frente
fc_mod5.treino
formattable(as_tibble(fc_mod5.treino))
par(mfrow=c(1,1)) ## apenas para organizar os gráficos
plot(fc_mod5.treino, include = 24, showgap = F, main = "Previsão do SARIMA
     (1,0,2)(1,1,1)", xlab = "Período")

accuracy(fc_mod5.treino$mean,emprego.teste)

## criar um data frame
df_test5 <- ts(data.frame(cbind(fcst=fc_mod5.treino$mean,obs=emprego.teste)))

## plotar o observado com a previsão
autoplot(df_test5[,2], series = "Observado") + 
  autolayer(df_test5[,1], series = "Previsão") +
  labs(title = "Emprego CLT (Período: Jan/2019 - Dez/2019)",
       x = "Períodos",
       y = "",
       color = "Previsão")

### Modelo 7

emprego.teste<- tail(emprego_ts[ ,2],12) ## observar apenas as últimas 12 observações                                   # definindo a série "teste"
emprego.teste

emprego.treino <- head(emprego_ts[ ,2], length(emprego_ts[ ,2])-12) ## pegar o começo da série               # definindo a série "treino"
emprego.treino

mod7.treino=Arima(emprego.treino, order=c(1,0,2), seasonal=list(order=c(2,1,1), period=12)); mod7.treino

fc_mod7.treino <- forecast(mod7.treino, h = 12) ## a partir da série treino, realizar a projeção para 12 períodos para frente
fc_mod7.treino
formattable(as_tibble(fc_mod7.treino))
par(mfrow=c(1,1)) ## apenas para organizar os gráficos
plot(fc_mod7.treino, include = 24, showgap = F, main = "Previsão do SARIMA
     (1,0,2)(2,1,1)", xlab = "Período")

accuracy(fc_mod7.treino$mean,emprego.teste)

## criar um data frame
df_test7 <- ts(data.frame(cbind(fcst=fc_mod7.treino$mean,obs=emprego.teste)))

## plotar o observado com a previsão
autoplot(df_test7[,2], series = "Observado") + 
  autolayer(df_test7[,1], series = "Previsão") +
  labs(title = "Emprego CLT (Período: Jan/2019 - Dez/2019)",
       x = "Períodos",
       y = "",
       color = "Previsão")



# Modelo X - essa parte será feita apenas após a definição do melhor modelo entre os demais
## Gráfico "manual"
fc_mod8 <- forecast(mod8, h = 12)
se8 <- sqrt(mod8$sigma2)

par(mfrow=c(1,1))
ts.plot(window(emprego_ts[ ,2], start=c(2018,1)),
        fc_mod8$mean,
        fc_mod8$mean+1.96*se8,
        fc_mod8$mean-1.96*se8,
        col=c(1,2,2,2), lty=c(1,1,2,2),
        gpars = list(main = "Intervalo de Confiança das Projeções do Emprego",
                     xlab = "Período"))

## Gráfico da função 'forecast'
plot(fc_mod8, main = "Série de Empregos CLT completa com previsão",
     xlab = "Período")

plot(fc_mod8, 
     main = "Previsão do Saldo de Empregos CLT no Brasil para 2020",
     xlab = "Período",
     include = 24, 
     showgap = F, 
     fcol = "orange",
     flty = "dashed")
```

